AVSUL: include/avsul/bitmap.h File Reference
bitmap.h File Reference
Bitmap array header file.
Data Structures
struct vi_bitmap
Macros
#define VI_BITMAP_FIELD_TYPE uint64_t
#define VI_BITMAP_FIELD_SIZE 64
#define VI_BITMAP_MAX_BIT_COUNT 2147483648
Functions
int vit_bitmap_tests (int argc, char *argv[])
void vit_bitmap_run_test (vi_bitmap *b, uint64_t bit)
void vit_for_each_callback (uint64_t bit, void *data)
bool vi_bitmap_create (vi_bitmap *b, uint64_t size)
Create a bitmap of the given size.
bool vi_bitmap_test (vi_bitmap *b, uint64_t bit_num)
Tests the state of the given bit.
bool vi_bitmap_set (vi_bitmap *b, uint64_t bit_num)
Sets the given bit.
bool vi_bitmap_clear (vi_bitmap *b, uint64_t bit_num)
Clears the given bit.
bool vi_bitmap_set_to (vi_bitmap *b, uint64_t bit_num, bool val)
Sets a bit to the given state.
void vi_bitmap_for_each_set (vi_bitmap *b, void(*func)(VI_BITMAP_FIELD_TYPE, void *), void *data)
Iterate through each bitmap value, sending the bit to the given callback.
Detailed Description
Bitmap array header file.
Author
Adam Holisky (adam..nosp@m.holi.nosp@m.sky@g.nosp@m.mail.nosp@m..com)
Version
0.1
Date
2026-03-07
Copyright
Copyright (c) 2026
Definition in file bitmap.h.
Macro Definition Documentation
VI_BITMAP_FIELD_SIZE
#define VI_BITMAP_FIELD_SIZE 64
Definition at line 19 of file bitmap.h.
VI_BITMAP_FIELD_TYPE
#define VI_BITMAP_FIELD_TYPE uint64_t
Definition at line 18 of file bitmap.h.
VI_BITMAP_MAX_BIT_COUNT
#define VI_BITMAP_MAX_BIT_COUNT 2147483648
Definition at line 23 of file bitmap.h.
Function Documentation
vi_bitmap_clear()
bool vi_bitmap_clear (vi_bitmap * b, uint64_t bit_num)
Clears the given bit.
Parameters
b Pointer to the bitmap struct
bit_num bit number to clear
Returns
true Success
false Failure
Definition at line 106 of file bitmap.c.
{
    return vi_bitmap_set_to( b, bit_num, false );
}
References vi_bitmap_set_to().
vi_bitmap_create()
bool vi_bitmap_create (vi_bitmap * b, uint64_t size)
Create a bitmap of the given size.
Parameters
size 1 through (max of size_t) bit fields. NOT 0-based.
Returns
bool true if successful, false otherwise
Definition at line 25 of file bitmap.c.
{
    if( b == NULL ) {
        printf( "vi_bitmap *b is NULL. Failing.\n" );
        return false;
    }
    if( size < 1 ) {
        printf( "Size must be 1 or greater. Failing.\n" );
        return false;
    }
    if( size >= VI_BITMAP_MAX_BIT_COUNT ) {
        printf( "Size must be under %ld, got %ld. Failing.\n", VI_BITMAP_MAX_BIT_COUNT, size );
        return false;
    }
    b->field_count = size / VI_BITMAP_FIELD_SIZE;
    if( size % VI_BITMAP_FIELD_SIZE != 0 ) {
        b->field_count++;
    }
    b->fields = vmalloc( sizeof(VI_BITMAP_FIELD_TYPE) * b->field_count );
    if( b->fields == NULL ) {
        printf( "b->fields is NULL. Failing.\n" );
        return false;
    }
    b->bit_count = size;
    memset( b->fields, 0, b->field_count * (VI_BITMAP_FIELD_SIZE/8) );
    printf( "size: %ld    field_count: %ld\n", size, b->field_count );
    return true;
}
References vi_bitmap::bit_count, vi_bitmap::field_count, vi_bitmap::fields, VI_BITMAP_FIELD_SIZE, VI_BITMAP_FIELD_TYPE, and VI_BITMAP_MAX_BIT_COUNT.
vi_bitmap_for_each_set()
void vi_bitmap_for_each_set (vi_bitmap * b, void(*)(VI_BITMAP_FIELD_TYPE, void *) func, void * data)
Iterate through each bitmap value, sending the bit to the given callback.
Parameters
b
func
data
Definition at line 154 of file bitmap.c.
{
    if( b == NULL ) {
        printf( "vi_bitmap *b is NULL. Failing.\n" );
        return;
    }
    for( uint64_t i = 0; i < b->bit_count; i++ ) {
        if( vi_bitmap_test(b,i) ) {
            func( i, data );
        }
    }
}
References vi_bitmap::bit_count, and vi_bitmap_test().
vi_bitmap_set()
bool vi_bitmap_set (vi_bitmap * b, uint64_t bit_num)
Sets the given bit.
Parameters
b Pointer to the bitmap struct
bit_num bit number to set
Returns
true Success
false Failure
Definition at line 94 of file bitmap.c.
{
    return vi_bitmap_set_to( b, bit_num, true );
}
References vi_bitmap_set_to().
vi_bitmap_set_to()
bool vi_bitmap_set_to (vi_bitmap * b, uint64_t bit_num, bool val)
Sets a bit to the given state.
Parameters
b Pointer to the bitmap struct
bit_num bit number to set
val true (1) or false (0)
Returns
true Success
false Failure
Definition at line 119 of file bitmap.c.
{
    uint32_t field = bit_num / VI_BITMAP_FIELD_SIZE;
    uint64_t bit = bit_num % VI_BITMAP_FIELD_SIZE;
    if( b == NULL ) {
        printf( "vi_bitmap *b is NULL. Failing.\n" );
        return false;
    }
    if( bit_num > b->bit_count ) {
        printf( "Bit number exceeded allocated size. bit_num = %d, max = %d.\n", bit_num, b->bit_count );
        return false;
    }
    // intentionally omitting field size check for speed sake, given b ought to be configured right by now
    if( val ) {
        // Set bit
        b->fields[field] = b->fields[field] | (1UL<<bit);
    } else {
        // Clear bit
        b->fields[field] = b->fields[field] & (0UL<<bit);
    }
    //printf( "setting field: %ld    bit: %d    set: %d (%llX)    field data: 0x%llX\n", field, bit, val, (1UL<<bit),b->fields[field] );
    return true;
}
References vi_bitmap::bit_count, vi_bitmap::fields, and VI_BITMAP_FIELD_SIZE.
Referenced by vi_bitmap_clear(), and vi_bitmap_set().
vi_bitmap_test()
bool vi_bitmap_test (vi_bitmap * b, uint64_t bit_num)
Tests the state of the given bit.
Parameters
b Pointer to the bitmap struct
bit_num bit number to test
Returns
true Bit is set
false Bit is unset
Definition at line 69 of file bitmap.c.
{
    uint32_t field = bit_num / VI_BITMAP_FIELD_SIZE;
    uint64_t bit = bit_num % VI_BITMAP_FIELD_SIZE;
    if( b == NULL ) {
        printf( "vi_bitmap *b is NULL. Failing.\n" );
        return false;
    }
    if( bit_num > b->bit_count ) {
        printf( "Bit number exceeded allocated size. bit_num = %d, max = %d.\n", bit_num, b->bit_count );
        return false;
    }
    return (b->fields[field] & (1UL<<bit)) >= 1 ? true : false;
}
References vi_bitmap::bit_count, vi_bitmap::fields, and VI_BITMAP_FIELD_SIZE.
Referenced by vi_bitmap_for_each_set().
vit_bitmap_run_test()
void vit_bitmap_run_test (vi_bitmap * b, uint64_t bit)
vit_bitmap_tests()
int vit_bitmap_tests (int argc, char * argv[])
vit_for_each_callback()
void vit_for_each_callback (uint64_t bit, void * data)